### ISSUE TITLE
add documentation to event-emitter

### ISSUE THREAD

**Issue by coolaj86** [neon-bindings/examples#27]
We have here a bunch of code, but no documentation: https://github.com/neon-bindings/examples/tree/master/event-emitter

It would be nice to know:

* How to build it? (probably something like `npm install neon; neon build`)
* How to use it? (probably something like `var EvEm = require("event-emitter"); ...`)

It looks like there's a lot of code there. Could we perhaps pare it down to just an event emitter example and split the polling and other stuff into a second example?

It's probably perfect as-is for a quick reference for those that are familiar with Rust and with neon and I may be very much in the minority, but I'm looking at neon as an excuse to become more familiar with Rust and although I know that what I need is right in front of me, I don't know enough to easily pick it out yet.

**Comment by coolaj86** [comment]
I spent some time going through this and either I'm completely misunderstanding what it does, or this isn't an event emitter at all.

It looks like it's simply exposing an async method `poll()` which puts an event onto a schedule and then calls the callback which was handed to `poll()`, and loops to call `poll()` again with a new function.

Is there anyway to adapt this so that the callback is called multiple times like an event emitter would be (i.e. getting data from a network socket) rather than having the upper level JS telling the lower level Rust to call the upper level JS?

Or how would I get data from a network socket on a regular basis? The data is coming in whether or not the JavaScript asks for it, which is what normally makes callbacks a nice pattern.

Ultimately I suppose that I do want a "pull" stream rather than a "push" stream, and maybe that's what this is really demonstrating, but I'd like to see how to have a looping thread in Rust fire a callback every 500ms. Here it looks like if I do a `setTimeout(poll, 1500)`, then the count doesn't continue to increment. Instead it sits and waits for the upper JS to tell it to continue its would-be background process.

**Comment by amilajack** [comment]
This example was taken [from here](https://github.com/kjvalencik/neon-example). @kjvalencik would be the best to answer this. See https://github.com/neon-bindings/neon/issues/386#issuecomment-454114366 for some details on it.

**Comment by kjvalencik** [comment]
@coolaj86 Hi! Sorry for the lack of documentation. This is something that I threw together quickly to provide as an example for someone in our slack channel. It's not as complete as a proper example should be.

Firstly, I should mention that this entire example is a hack around a missing feature in Neon. Namely, there is no way to schedule code to execute on the main JS thread. This is something that is being considered.

https://github.com/neon-bindings/rfcs/pull/25
https://github.com/neon-bindings/neon/pull/375

Next, this example has a lot of code that isn't relevant to the event emitter example. The part that is relevant to the `EventEmitter`: https://github.com/neon-bindings/examples/blob/84b125c7cd3ff89b9272eedce1e2a6f551ac36ae/event-emitter/native/src/lib.rs#L158-L262

High level, since a Rust thread can't call into JS, something from JS needs to call into Rust. This is what the poll API provides.

The `event_thread` method simulates a long running process that sends data to a [Channel](https://doc.rust-lang.org/beta/std/sync/mpsc/index.html). In this example, the channel is unbounded and will continue to accumulate data if it's not read from. In your example, this would be a Rust thread reading from a network socket and sending the bytes on the channel.
https://github.com/neon-bindings/examples/blob/84b125c7cd3ff89b9272eedce1e2a6f551ac36ae/event-emitter/native/src/lib.rs#L162

The `poll` method exposed from Neon reads from the channel. It uses a blocking read that waits indefinitely for data to be available. This is why it's an asynchronous method. We don't want to block the event loop while waiting for data. However, it's still taking a LIB_UV thread, so ideally it would yield occasionally anyway.

The data that is being written to the channel looks like `{ event: string, ...data }`. The `EventEmitter` JS code is glue code to convert the `poll` interface into something that is more typical JS. It `polls` in a loop, taking data each time and emitting an event with `this.emit(event, data)`.
https://github.com/neon-bindings/examples/blob/84b125c7cd3ff89b9272eedce1e2a6f551ac36ae/event-emitter/lib/emitter.js#L20

With the glue code out of the way, a consumer of the event emitter can subscribe to events.
https://github.com/neon-bindings/examples/blob/84b125c7cd3ff89b9272eedce1e2a6f551ac36ae/event-emitter/lib/emitter.js#L36

In your use case, it might make more sense to adapt a stream interface rather than an `EventEmitter`.

I hope this helps!

**Comment by coolaj86** [comment]
Wow! Thanks so much.

**Comment by msansoni** [comment]
Thanks for everything on this example! However I'm struggling with the example erroring out:
```
>domain.js:129
domain.enter();
TypeError: domain.enter is not a function
```
It appears to be as a result of the attempted task scheduling in the rust module:
https://github.com/neon-bindings/examples/blob/f76cd9800f38bc08a339705972a5a79e7b6a3f5d/event-emitter/native/src/lib.rs#L180
